spring:
  application:
    name: dubbo-demo-consumer
s: 3
dubbo:
  registry:
    address: zookeeper://master:2290
  application:
    name: dubbo-demo
  config-center:
    address: zookeeper://master:2290
  metadata-report:
    address: zookeeper://master:2290
